# BÀI TẬP CHƯƠNG 2

## Nhập hai bảng student(student_id, name, class, course_id, score) và course(id, course_name)

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('dung.db')
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS student (
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS course (
    id INTEGER,
    course_name TEXT
)
""")

students = [
(1,"Nguyen Minh Hoang","May Tinh",12,6.7),
(2,"Tran Thi Lan","Kinh Te",34,9.2),
(3,"Pham Van Nam","Toan Tin",None,7.9),
(4,"Le Thanh Huyen","Toan Tin",20,7.2),
(5,"Vu Quoc Anh","May Tinh",24,8.0),
(6,"Dang Thuy Linh","May Tinh",24,5.5),
(7,"Bui Tien Dung","Kinh Te",34,9.2),
(8,"Ho Ngoc Mai","Toan Tin",20,8.8),
(9,"Duong Huu Phuc","Kinh Te",None,7.2),
(10,"Cao Thi Hanh","May Tinh",None,7.0)
]

cursor.executemany("INSERT INTO student VALUES (?,?,?,?,?)",students)

courses = [
(12,"Giai tich"),
(34,"Thong ke"),
(26,"Tin hoc")
]

cursor.executemany("INSERT INTO course VALUES (?,?)",courses)

conn.commit()

## 1. Kết nối 2 bảng theo những cách:
### -Sử dụng tích Decartes.
### -Sử dụng JOIN: INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN

### Sử dụng tích Decartes:

In [2]:
query = """
SELECT *
FROM student
CROSS JOIN course
"""
pd.read_sql(query,conn)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

### INNER JOIN:

In [3]:
query = """
SELECT *
FROM student s
INNER JOIN course c
ON s.course_id = c.id
"""
pd.read_sql(query,conn)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

### LEFT JOIN:

In [4]:
query = """
SELECT *
FROM student s
LEFT JOIN course c
ON s.course_id = c.id
"""
pd.read_sql(query,conn)

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

### RIGHT JOIN:

In [5]:
query = """
SELECT *
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
"""
pd.read_sql(query,conn)

   id course_name  student_id               name     class  course_id  score
0  12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
1  34    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
2  34    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
3  26     Tin hoc         NaN               None      None        NaN    NaN

### FULL OUTER JOIN:

In [6]:
query = """
SELECT *
FROM student s
LEFT JOIN course c
ON s.course_id = c.id

UNION

SELECT *
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
"""
pd.read_sql(query,conn)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,12.0,Giai tich
1,2,Tran Thi Lan,Kinh Te,34,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,None,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20,7.2,NaN,None
4,5,Vu Quoc Anh,May Tinh,24,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,NaN,None
8,9,Duong Huu Phuc,Kinh Te,None,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,None,7.0,NaN,None
10,12,Giai tich,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
11,26,Tin hoc,None,None,None,NaN,None
12,34,Thong ke,2,Tran Thi Lan,Kinh Te,34.0,9.2
13,34,Thong ke,7,Bui Tien Dung,Kinh Te,34.0,9.2

## 2. Hãy cập nhật những giá trị course_id còn thiếu trong bảng student bằng câu lệnh SQL, trong đó các giá trị được điền là những giá trị nằm trong bảng course và loại bỏ những bản ghi tham gia những môn học không tồn tại bảng course. Sau đó hãy cho biết:
### a. Tổng số sinh viên, điểm trung bình của từng lớp.
### b. Tổng số sinh viên, điểm trung bình của từng môn học.
### c. Phân loại thi đua theo số điểm của từng môn học biết:
#### i. Điểm TB ≥ 9.0: Xuất sắc.
#### ii. 6.0 ≤ Điểm TB ≤ 8.9: Tốt.
#### iii. Điểm TB < 6.0: Kém.

### Cập nhật course_id còn thiếu:

In [7]:
cursor.execute("""
UPDATE student
SET course_id = 26
WHERE course_id IS NULL
""")

conn.commit()

pd.read_sql("SELECT * FROM student", conn)

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         26    7.9
3           4     Le Thanh Huyen  Toan Tin         20    7.2
4           5        Vu Quoc Anh  May Tinh         24    8.0
5           6     Dang Thuy Linh  May Tinh         24    5.5
6           7      Bui Tien Dung   Kinh Te         34    9.2
7           8        Ho Ngoc Mai  Toan Tin         20    8.8
8           9     Duong Huu Phuc   Kinh Te         26    7.2
9          10       Cao Thi Hanh  May Tinh         26    7.0

### Loại bỏ những bản ghi tham gia những môn học không tồn tại bảng course

In [8]:
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (
SELECT id FROM course
)
""")

conn.commit()

pd.read_sql("SELECT * FROM student", conn)

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         26    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         26    7.2
5          10       Cao Thi Hanh  May Tinh         26    7.0

### a. Tổng số sinh viên, điểm trung bình của từng lớp

In [9]:
query = """
SELECT
class,
COUNT(*) AS total_students,
AVG(score) AS avg_score
FROM student
GROUP BY class
"""

pd.read_sql(query, conn)

      class  total_students  avg_score
0   Kinh Te               3   8.533333
1  May Tinh               2   6.850000
2  Toan Tin               1   7.900000

### b. Tổng số sinh viên, điểm trung bình của từng môn học.

In [10]:
query = """
SELECT
c.course_name,
COUNT(s.student_id) AS total_students,
AVG(s.score) AS avg_score
FROM student s
JOIN course c
ON s.course_id = c.id
GROUP BY c.course_name
"""

pd.read_sql(query, conn)

  course_name  total_students  avg_score
0   Giai tich               1   6.700000
1    Thong ke               2   9.200000
2     Tin hoc               3   7.366667

### c. Phân loại thi đua theo số điểm của từng môn học

In [11]:
query = """
SELECT
name,
score,
CASE
WHEN score >= 9 THEN 'Xuat sac'
WHEN score >= 6 AND score <= 8.9 THEN 'Tot'
ELSE 'Kem'
END AS classification
FROM student
"""

pd.read_sql(query, conn)

                name  score classification
0  Nguyen Minh Hoang    6.7            Tot
1       Tran Thi Lan    9.2       Xuat sac
2       Pham Van Nam    7.9            Tot
3      Bui Tien Dung    9.2       Xuat sac
4     Duong Huu Phuc    7.2            Tot
5       Cao Thi Hanh    7.0            Tot

## 3. Hãy xếp hạng sinh viên thông qua:
### a. Điểm số.
### b. Điểm số theo lớp học.
### c. Điểm số theo mã môn học.
## và cho biết top 3 sinh viên đạt thứ hạng cao nhất, top 3 sinh viên đạt thứ hạng thấp nhất theo từng trường hợp trên.

### a. Xếp hạng sinh viên theo điểm số:

In [17]:
query = """
SELECT
student_id,
name,
class,
course_id,
score,
RANK() OVER (ORDER BY score DESC) AS rank_score
FROM student
"""

pd.read_sql(query, conn)

   student_id               name     class  course_id  score  rank_score
0           2       Tran Thi Lan   Kinh Te         34    9.2           1
1           7      Bui Tien Dung   Kinh Te         34    9.2           1
2           3       Pham Van Nam  Toan Tin         26    7.9           3
3           9     Duong Huu Phuc   Kinh Te         26    7.2           4
4          10       Cao Thi Hanh  May Tinh         26    7.0           5
5           1  Nguyen Minh Hoang  May Tinh         12    6.7           6

#### Top 3 sinh viên đạt thứ hạng cao nhất:

In [20]:
query = """
SELECT *
FROM (
SELECT
student_id,
name,
class,
course_id,
score,
RANK() OVER (ORDER BY score DESC) AS rank_score
FROM student
)
WHERE rank_score <= 3
"""
pd.read_sql(query, conn)

   student_id           name     class  course_id  score  rank_score
0           2   Tran Thi Lan   Kinh Te         34    9.2           1
1           7  Bui Tien Dung   Kinh Te         34    9.2           1
2           3   Pham Van Nam  Toan Tin         26    7.9           3

#### Top 3 sinh viên đạt thứ hạng thấp nhất

In [22]:
query = """
SELECT *
FROM (
SELECT
student_id,
name,
class,
course_id,
score,
RANK() OVER (ORDER BY score ASC) AS rank_score
FROM student
)
WHERE rank_score <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  rank_score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7           1
1          10       Cao Thi Hanh  May Tinh         26    7.0           2
2           9     Duong Huu Phuc   Kinh Te         26    7.2           3

### b. Xếp hạng sinh viên theo điểm số theo lớp học

In [32]:
query = """
SELECT
student_id,
name,
class,
score,
RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_class
FROM student
"""
pd.read_sql(query, conn)

   student_id               name     class  score  rank_class
0           2       Tran Thi Lan   Kinh Te    9.2           1
1           7      Bui Tien Dung   Kinh Te    9.2           1
2           9     Duong Huu Phuc   Kinh Te    7.2           3
3          10       Cao Thi Hanh  May Tinh    7.0           1
4           1  Nguyen Minh Hoang  May Tinh    6.7           2
5           3       Pham Van Nam  Toan Tin    7.9           1

#### Top 3 cao nhất theo từng lớp

In [31]:
query = """
SELECT *
FROM (
SELECT
student_id,
name,
class,
score,
RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_class
FROM student
)
WHERE rank_class <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  score  rank_class
0           2       Tran Thi Lan   Kinh Te    9.2           1
1           7      Bui Tien Dung   Kinh Te    9.2           1
2           9     Duong Huu Phuc   Kinh Te    7.2           3
3          10       Cao Thi Hanh  May Tinh    7.0           1
4           1  Nguyen Minh Hoang  May Tinh    6.7           2
5           3       Pham Van Nam  Toan Tin    7.9           1

#### Top 3 thấp nhất theo từng lớp

In [30]:
query = """
SELECT *
FROM (
SELECT
student_id,
name,
class,
score,
RANK() OVER (PARTITION BY class ORDER BY score ASC) AS rank_class
FROM student
)
WHERE rank_class <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  score  rank_class
0           9     Duong Huu Phuc   Kinh Te    7.2           1
1           2       Tran Thi Lan   Kinh Te    9.2           2
2           7      Bui Tien Dung   Kinh Te    9.2           2
3           1  Nguyen Minh Hoang  May Tinh    6.7           1
4          10       Cao Thi Hanh  May Tinh    7.0           2
5           3       Pham Van Nam  Toan Tin    7.9           1

### c. Xếp hạng sinh viên theo điểm số theo mã môn học

In [29]:
query = """
SELECT
student_id,
name,
course_id,
score,
RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_course
FROM student
"""
pd.read_sql(query, conn)

   student_id               name  course_id  score  rank_course
0           1  Nguyen Minh Hoang         12    6.7            1
1           3       Pham Van Nam         26    7.9            1
2           9     Duong Huu Phuc         26    7.2            2
3          10       Cao Thi Hanh         26    7.0            3
4           2       Tran Thi Lan         34    9.2            1
5           7      Bui Tien Dung         34    9.2            1

#### Top 3 cao nhất theo môn

In [33]:
query = """
SELECT *
FROM (
SELECT
student_id,
name,
course_id,
score,
RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_course
FROM student
)
WHERE rank_course <= 3
"""
pd.read_sql(query, conn)

   student_id               name  course_id  score  rank_course
0           1  Nguyen Minh Hoang         12    6.7            1
1           3       Pham Van Nam         26    7.9            1
2           9     Duong Huu Phuc         26    7.2            2
3          10       Cao Thi Hanh         26    7.0            3
4           2       Tran Thi Lan         34    9.2            1
5           7      Bui Tien Dung         34    9.2            1

#### Top 3 thấp nhất theo môn

In [34]:
query = """
SELECT *
FROM (
SELECT
student_id,
name,
course_id,
score,
RANK() OVER (PARTITION BY course_id ORDER BY score ASC) AS rank_course
FROM student
)
WHERE rank_course <= 3
"""
pd.read_sql(query, conn)

   student_id               name  course_id  score  rank_course
0           1  Nguyen Minh Hoang         12    6.7            1
1          10       Cao Thi Hanh         26    7.0            1
2           9     Duong Huu Phuc         26    7.2            2
3           3       Pham Van Nam         26    7.9            3
4           2       Tran Thi Lan         34    9.2            1
5           7      Bui Tien Dung         34    9.2            1

## 4. Hãy bổ sung thêm một trường graduation_date có kiểu dữ liệu là DATETIME vào bảng student để xác định thời gian tốt nghiệp của từng bạn, trong đó thời gian tốt nghiệp được xác định bởi thời gian hiện tại cộng với số hạng tương ứng của bạn đó tính theo điểm số.

### Thêm cột graduation_date

In [35]:
cursor.execute("""
ALTER TABLE student
ADD COLUMN graduation_date DATETIME
""")

conn.commit()

### Tính thứ hạng theo điểm số

In [36]:
query = """
SELECT
student_id,
name,
score,
RANK() OVER (ORDER BY score DESC) AS rank_score
FROM student
"""

pd.read_sql(query, conn)

   student_id               name  score  rank_score
0           2       Tran Thi Lan    9.2           1
1           7      Bui Tien Dung    9.2           1
2           3       Pham Van Nam    7.9           3
3           9     Duong Huu Phuc    7.2           4
4          10       Cao Thi Hanh    7.0           5
5           1  Nguyen Minh Hoang    6.7           6

In [37]:
cursor.execute("""
UPDATE student
SET graduation_date =
datetime('now','+' || (
SELECT rank_score
FROM (
SELECT student_id,
RANK() OVER (ORDER BY score DESC) AS rank_score
FROM student
) r
WHERE r.student_id = student.student_id
) || ' days')
""")

conn.commit()

In [38]:
pd.read_sql("""
SELECT
student_id,
name,
score,
graduation_date
FROM student
ORDER BY score DESC
""", conn)

   student_id               name  score      graduation_date
0           2       Tran Thi Lan    9.2  2026-04-03 17:02:01
1           7      Bui Tien Dung    9.2  2026-04-03 17:02:01
2           3       Pham Van Nam    7.9  2026-04-05 17:02:01
3           9     Duong Huu Phuc    7.2  2026-04-06 17:02:01
4          10       Cao Thi Hanh    7.0  2026-04-07 17:02:01
5           1  Nguyen Minh Hoang    6.7  2026-04-08 17:02:01